const mockPets = [
  {
    id: 1,
    name: "Bailey",
    age: "Adult",
    ageYears: 5,
    breed: "Corgi",
    location: "Brooklyn, NY",
    type: "dog",
    img: import.meta.env.BASE_URL + "corgi.jpg",
  },
  {
    id: 2,
    name: "Luna",
    age: "Young",
    ageYears: 2,
    breed: "German Shepherd",
    location: "Brooklyn, NY",
    type: "dog",
    img: import.meta.env.BASE_URL + "german-shepherd.jpg",
  },
  {
    id: 3,
    name: "Rosie",
    age: "Adult",
    ageYears: 4,
    breed: "Pit Bull",
    location: "Manhattan, NY",
    type: "dog",
    img: import.meta.env.BASE_URL + "pitbull.jpg",
  },
  {
    id: 4,
    name: "Mittens",
    age: "Kitten",
    ageYears: 0,
    breed: "Domestic Short Hair",
    location: "Brooklyn, NY",
    type: "cat",
    img: import.meta.env.BASE_URL + "domestic-shorthair.jpg",
  },
  {
    id: 5,
    name: "Oliver",
    age: "Adult",
    ageYears: 3,
    breed: "Tabby",
    location: "Queens, NY",
    type: "cat",
    img: import.meta.env.BASE_URL + "tabby.jpg",
  },
  {
    id: 6,
    name: "Snowball",
    age: "Senior",
    ageYears: 10,
    breed: "Persian",
    location: "Bronx, NY",
    type: "cat",
    img: import.meta.env.BASE_URL + "persian.jpg",
  },
  {
    id: 7,
    name: "Sky",
    age: "Adult",
    ageYears: 2,
    breed: "Parakeet",
    location: "Queens, NY",
    type: "bird",
    img: import.meta.env.BASE_URL + "parakeet.jpg",
  },
  {
    id: 8,
    name: "Sunny",
    age: "Adult",
    ageYears: 3,
    breed: "Cockatiel",
    location: "Brooklyn, NY",
    type: "bird",
    img: import.meta.env.BASE_URL + "cockatiel.jpg",
  },
  {
    id: 9,
    name: "Kiwi",
    age: "Young",
    ageYears: 1,
    breed: "Lovebird",
    location: "Manhattan, NY",
    type: "bird",
    img: import.meta.env.BASE_URL + "lovebird.jpg",
  },
];

export default mockPets;
